# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lm_fast_cpp <- function(X, y) {
    .Call('_itnb_lm_fast_cpp', PACKAGE = 'itnb', X, y)
}

em_itnb_cpp <- function(X, y, yi, beta_0, theta_0, p_0, i, t, link, iteration_min, iteration_max, tolerance, lambda, steps, exact, trace, save_trace) {
    .Call('_itnb_em_itnb_cpp', PACKAGE = 'itnb', X, y, yi, beta_0, theta_0, p_0, i, t, link, iteration_min, iteration_max, tolerance, lambda, steps, exact, trace, save_trace)
}

mle_itnb_cpp <- function(X, y, beta_0, theta_0, p_0, i, t, link, tolerance, lambda, steps, exact, trace) {
    .Call('_itnb_mle_itnb_cpp', PACKAGE = 'itnb', X, y, beta_0, theta_0, p_0, i, t, link, tolerance, lambda, steps, exact, trace)
}

ritnb_cpp <- function(n, mu, theta, p, i, t) {
    .Call('_itnb_ritnb_cpp', PACKAGE = 'itnb', n, mu, theta, p, i, t)
}

ditnb_cpp <- function(x, mu, theta, p, i, t) {
    .Call('_itnb_ditnb_cpp', PACKAGE = 'itnb', x, mu, theta, p, i, t)
}

pitnb_cpp <- function(x, mu, theta, p, i, t) {
    .Call('_itnb_pitnb_cpp', PACKAGE = 'itnb', x, mu, theta, p, i, t)
}

