# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

complete_loglikelihood <- function(x, xi, z, mu, theta, p, i, t) {
    .Call('_itnb_complete_loglikelihood', PACKAGE = 'itnb', x, xi, z, mu, theta, p, i, t)
}

restricted_loglikelihood <- function(x, z, mu, theta, p, i, t) {
    .Call('_itnb_restricted_loglikelihood', PACKAGE = 'itnb', x, z, mu, theta, p, i, t)
}

em_itnb_cpp <- function(x, xi, mu_0, theta_0, p_0, i, t, iteration_min, iteration_max, tolerance, trace, save_trace) {
    .Call('_itnb_em_itnb_cpp', PACKAGE = 'itnb', x, xi, mu_0, theta_0, p_0, i, t, iteration_min, iteration_max, tolerance, trace, save_trace)
}

ritnb_cpp <- function(n, mu, theta, p, i, t) {
    .Call('_itnb_ritnb_cpp', PACKAGE = 'itnb', n, mu, theta, p, i, t)
}

ditnb_cpp <- function(x, mu, theta, p, i, t) {
    .Call('_itnb_ditnb_cpp', PACKAGE = 'itnb', x, mu, theta, p, i, t)
}

pitnb_cpp <- function(x, mu, theta, p, i, t) {
    .Call('_itnb_pitnb_cpp', PACKAGE = 'itnb', x, mu, theta, p, i, t)
}

